platform :ios, '8.0'
use_frameworks!

target 'AppAnimal' do
	pod 'Alamofire', '2.0'
	pod 'SwiftyJSON', :git => 'https://github.com/SwiftyJSON/SwiftyJSON.git'
    pod 'AWSCognito'
    pod 'AWSS3', '~> 2.2.0'
end
